# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  workflow_dispatch:
  
  repository_dispatch:
    types:
      - webhook

jobs:
  pre-job:
    name: Pre-job
    runs-on: ubuntu-latest

    steps:
      - uses: technote-space/auto-cancel-redundant-workflow@v1
      - name: Cancel redundant workflows
        run: echo "Cancel redundant workflows finished"
          
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Blog Post Workflow
        uses: gautamkrishnar/blog-post-workflow@1.5.6
        with:
          gh_token: ${{ github.token }}
          feed_list: https://www.reddit.com/r/2600.rss,https://2600.com/rss.xml
          readme_path: ./profile/README.md
